import React, { useEffect, useState } from 'react'
import { Link, useParams } from 'react-router-dom'
import { ArrowLeft, Briefcase as BriefcaseBusiness, Clock3, MapPin, Send, Users } from 'lucide-react'
import { apiClient } from '@services/api'
import { JobDetail } from '@/types'

const JobDetailPage: React.FC = () => {
  const { id } = useParams(); const [job, setJob] = useState<JobDetail | null>(null); const [error, setError] = useState(''); const [loading, setLoading] = useState(true)
  useEffect(() => { if (!id) return; apiClient.getJobById(id).then(r => setJob(r.data.data)).catch(() => setError('This role is no longer available.')).finally(() => setLoading(false)) }, [id])
  if (loading) return <div className="section container py-24 text-center text-slate-500">Loading role…</div>
  if (error || !job) return <div className="section container"><Link to="/jobs" className="text-sm font-bold text-indigo-600">← Back to jobs</Link><div className="card mt-6 py-16 text-center text-rose-600">{error}</div></div>
  return <div className="section container"><Link to="/jobs" className="inline-flex items-center gap-2 text-sm font-bold text-indigo-600"><ArrowLeft size={16} /> All opportunities</Link><div className="mt-6 grid gap-8 lg:grid-cols-[1fr_340px]"><article className="card sm:p-8"><div className="flex items-start gap-4"><span className="grid h-14 w-14 place-items-center rounded-2xl bg-indigo-50 text-indigo-600"><BriefcaseBusiness size={25} /></span><div><span className="text-xs font-bold uppercase tracking-wider text-emerald-600">{job.isClosed ? 'Applications closed' : 'Now hiring'}</span><h1 className="mt-1 text-3xl font-bold tracking-tight">{job.title}</h1><Link to={`/company/${job.companyId}`} className="mt-2 inline-block font-semibold text-indigo-600">{job.companyName || 'HireSphere partner'}</Link></div></div><div className="mt-8 flex flex-wrap gap-x-6 gap-y-3 border-y border-slate-100 py-5 text-sm text-slate-600"><span className="flex items-center gap-2"><MapPin size={17} /> {job.location || 'Flexible location'}</span><span className="flex items-center gap-2"><Clock3 size={17} /> Posted {new Date(job.createdAt).toLocaleDateString()}</span><span className="flex items-center gap-2"><Users size={17} /> {job.applicationCount} applicants</span></div><section className="mt-8"><h2 className="text-xl font-bold">About the role</h2><p className="mt-4 whitespace-pre-line leading-8 text-slate-600">{job.description}</p></section>{job.requiredSkills?.length ? <section className="mt-8"><h2 className="text-xl font-bold">Skills that help</h2><div className="mt-4 flex flex-wrap gap-2">{job.requiredSkills.map(skill => <span key={skill.id} className="rounded-full bg-indigo-50 px-3 py-1.5 text-sm font-semibold text-indigo-700">{skill.name}</span>)}</div></section> : null}</article><aside><div className="card sticky top-24"><h2 className="text-lg font-bold">Interested in this role?</h2><p className="mt-2 text-sm leading-6 text-slate-500">Share your profile and let the team know why you are a great fit.</p><button disabled={job.isClosed} className="btn btn-primary mt-6 w-full"><Send size={17} /> {job.isClosed ? 'Applications closed' : 'Apply now'}</button><p className="mt-4 text-center text-xs text-slate-400">Sign in as a candidate to apply.</p></div></aside></div></div>
}
export default JobDetailPage
