import React, { useEffect, useMemo, useState } from 'react'
import { Link } from 'react-router-dom'
import { Briefcase as BriefcaseBusiness, MapPin, Search, SlidersHorizontal, Users } from 'lucide-react'
import { apiClient } from '@services/api'
import { JobListResponse } from '@/types'

const JobListingPage: React.FC = () => {
  const [jobs, setJobs] = useState<JobListResponse[]>([]); const [loading, setLoading] = useState(true); const [error, setError] = useState(''); const [query, setQuery] = useState(''); const [filter, setFilter] = useState<'all' | 'active'>('active')
  useEffect(() => { apiClient.getJobs().then(r => setJobs(r.data.data || [])).catch(() => setError('We could not load roles just now. Please try again.')).finally(() => setLoading(false)) }, [])
  const shown = useMemo(() => jobs.filter(j => (filter === 'all' || !j.isClosed) && `${j.title} ${j.companyName} ${j.location}`.toLowerCase().includes(query.toLowerCase())), [jobs, filter, query])
  return <div className="section container"><div className="rounded-3xl bg-slate-950 px-6 py-10 text-white sm:px-10"><p className="eyebrow !text-indigo-300">Opportunity board</p><h1 className="mt-2 text-3xl font-bold sm:text-4xl">Find a role that feels right.</h1><p className="mt-3 max-w-xl text-slate-300">Explore openings from growing teams and established companies.</p><div className="mt-7 flex items-center gap-3 rounded-2xl bg-white p-2 text-slate-800"><Search className="ml-2 text-slate-400" size={20} /><input value={query} onChange={e => setQuery(e.target.value)} className="w-full bg-transparent py-2 outline-none" placeholder="Role, company, or location" /><span className="hidden rounded-xl bg-indigo-600 px-4 py-2 text-sm font-semibold text-white sm:block">Search</span></div></div>
    <div className="mt-8 flex flex-wrap items-center justify-between gap-4"><div className="flex gap-2"><button onClick={() => setFilter('active')} className={`rounded-xl px-4 py-2 text-sm font-semibold ${filter === 'active' ? 'bg-indigo-600 text-white' : 'bg-white text-slate-600 border border-slate-200'}`}>Open roles</button><button onClick={() => setFilter('all')} className={`rounded-xl px-4 py-2 text-sm font-semibold ${filter === 'all' ? 'bg-indigo-600 text-white' : 'bg-white text-slate-600 border border-slate-200'}`}>All roles</button></div><span className="flex items-center gap-2 text-sm text-slate-500"><SlidersHorizontal size={16} /> {shown.length} roles</span></div>
    {loading ? <p className="py-16 text-center text-slate-500">Loading opportunities…</p> : error ? <p className="py-16 text-center text-rose-600">{error}</p> : <div className="mt-6 grid gap-5 md:grid-cols-2 xl:grid-cols-3">{shown.map(job => <article key={job.id} className="card flex flex-col transition hover:-translate-y-1 hover:shadow-lg"><div className="flex items-start justify-between gap-3"><span className="grid h-11 w-11 shrink-0 place-items-center rounded-xl bg-indigo-50 text-indigo-600"><BriefcaseBusiness size={20} /></span><span className={`rounded-full px-3 py-1 text-xs font-bold ${job.isClosed ? 'bg-slate-100 text-slate-500' : 'bg-emerald-50 text-emerald-700'}`}>{job.isClosed ? 'Closed' : 'Hiring'}</span></div><h2 className="mt-5 text-lg font-bold text-slate-900">{job.title}</h2><p className="mt-1 text-sm font-medium text-indigo-600">{job.companyName || 'HireSphere partner'}</p><p className="mt-4 flex items-center gap-2 text-sm text-slate-500"><MapPin size={16} /> {job.location || 'Flexible location'}</p><div className="mt-5 flex items-center justify-between border-t border-slate-100 pt-4"><span className="flex items-center gap-1 text-xs text-slate-500"><Users size={15} /> {job.applicationCount} applicants</span><Link to={`/job/${job.id}`} className="text-sm font-bold text-indigo-600">View role →</Link></div></article>)}</div>}
    {!loading && !error && shown.length === 0 && <div className="card mt-6 py-16 text-center"><h2 className="text-lg font-bold">No roles found</h2><p className="mt-2 text-slate-500">Try a different search or view all roles.</p></div>}
  </div>
}
export default JobListingPage
